In [1]:
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from sklearn import datasets

In [5]:
from sklearn import svm

In [6]:
iris = datasets.load_iris()

In [7]:
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [8]:
X_train, X_test, y_train, y_test= train_test_split(
    iris.data, iris.target, test_size=0.4, random_state=0)

In [9]:
X_train.shape, y_train.shape

((90, 4), (90,))

In [10]:
X_test.shape, y_test.shape

((60, 4), (60,))

In [11]:
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)

In [12]:
clf.score(X_test, y_test)

0.96666666666666667

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
clf = svm.SVC(kernel='linear', C=1)

In [16]:
scores= cross_val_score(clf, iris.data, iris.target, cv=5)

In [17]:
scores

array([ 0.96666667,  1.        ,  0.96666667,  0.96666667,  1.        ])

In [18]:
print("Accuracy: %0.2f (+/- %0.2f)"% (scores.mean(), scores.std() *2))

Accuracy: 0.98 (+/- 0.03)


In [19]:
from sklearn import metrics

In [20]:
scores = cross_val_score(clf, iris.data, iris.target, cv=5, scoring='f1_macro')

In [21]:
scores

array([ 0.96658312,  1.        ,  0.96658312,  0.96658312,  1.        ])

In [22]:
from sklearn.model_selection import ShuffleSplit

In [23]:
n_samples  = iris.data.shape[0]

In [24]:
cv = ShuffleSplit(n_splits=3, test_size=0.3, random_state=0)

In [25]:
cross_val_score(clf, iris.data, iris.target, cv=cv)

array([ 0.97777778,  0.97777778,  1.        ])

In [26]:
from sklearn import preprocessing

In [27]:
X_train, X_test, y_train, y_test = train_test_split( 
   iris.data, iris.target, test_size=0.4, random_state=0)

In [28]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [29]:
X_train_transformed = scaler.transform(X_train)

In [30]:
clf = svm.SVC(C=1).fit(X_train_transformed, y_train)

In [31]:
X_test_transformed = scaler.transform(X_test)

In [32]:
clf.score(X_test_transformed, y_test)

0.93333333333333335

In [33]:
from sklearn.model_selection import cross_validate

In [34]:
from sklearn.metrics import recall_score

In [35]:
scoring = ['precision_macro', 'recall_macro']

In [36]:
clf = svm.SVC(kernel='linear', C=1, random_state=0)

In [37]:
scores = cross_validate(clf, iris.data, iris.target, scoring=scoring,
                       cv=5, return_train_score=False)

In [38]:
sorted(scores.keys())

['fit_time', 'score_time', 'test_precision_macro', 'test_recall_macro']

In [39]:
scores['test_recall_macro']

array([ 0.96666667,  1.        ,  0.96666667,  0.96666667,  1.        ])

In [40]:
from sklearn.metrics.scorer import make_scorer

In [41]:
scoring = {'prec_macro': 'precision_macro',
        'rec_micro': make_scorer(recall_score, average='macro')}

In [42]:
scores = cross_validate(clf, iris.data, iris.target, scoring=scoring,
                       cv=5, return_train_score=True)

In [43]:
sorted(scores.keys())

['fit_time',
 'score_time',
 'test_prec_macro',
 'test_rec_micro',
 'train_prec_macro',
 'train_rec_micro']

In [44]:
scores['train_rec_micro']

array([ 0.975     ,  0.975     ,  0.99166667,  0.98333333,  0.98333333])

In [45]:
import numpy as np

In [46]:
from sklearn.model_selection import KFold

In [47]:
X = ["a", "b", "c", "d"]

In [48]:
kf = KFold(n_splits=2)

In [53]:
for train, test in kf.split(X):
    print("%s%s"% (train, test))

[2 3][0 1]
[0 1][2 3]


In [50]:
X = np.array([[0., 0.], [1., 1.], [-1., -1.], [2., 2.]])

In [51]:
y = np.array([0, 1, 0, 1])

In [52]:
X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]