In [1]:
#Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
# view the features
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
# view the head of the file
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
# all the independent variables stored in columns 3 to 12 
# are stored in X 
X = dataset.iloc[:, 3:13].values

In [6]:
# column index 13 : the dependent variables
y = dataset.iloc[:, 13].values 

In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [9]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [10]:
# geography column: enumerate countries
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [11]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [12]:
# gender column: enumerate female/male
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [13]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ..., 
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [14]:
# encode enumerations to switch tables to prevent conflicts
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

In [15]:
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ..., 
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

In [16]:
# remove the first column to avoid the dummy variable trap
X = X[:, 1:] 

In [17]:
X

array([[  0.00000000e+00,   0.00000000e+00,   6.19000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  0.00000000e+00,   1.00000000e+00,   6.08000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  0.00000000e+00,   0.00000000e+00,   5.02000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   7.09000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  1.00000000e+00,   0.00000000e+00,   7.72000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  0.00000000e+00,   0.00000000e+00,   7.92000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

In [18]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [20]:
X_train

array([[  0.00000000e+00,   1.00000000e+00,   6.67000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.63830640e+05],
       [  1.00000000e+00,   0.00000000e+00,   4.27000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   5.70980000e+04],
       [  0.00000000e+00,   0.00000000e+00,   5.35000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.85630760e+05],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   7.38000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.81429870e+05],
       [  0.00000000e+00,   1.00000000e+00,   5.90000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.48750160e+05],
       [  1.00000000e+00,   0.00000000e+00,   6.23000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.18855260e+05]])

In [21]:
# Feature Scaling
from sklearn. preprocessing import StandardScaler

In [22]:
sc = StandardScaler()

In [23]:
X_train = sc.fit_transform(X_train)

In [24]:
X_test = sc.transform(X_test)

In [25]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ..., 
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [26]:
# Importing the Keras libraries and packages
import keras

Using TensorFlow backend.


In [27]:
from keras.models import Sequential

In [28]:
from keras.layers import Dense

In [29]:
# Initialising the ANN
#classifier = Sequential()

In [30]:
# Adding the input layer and the first hidden layer
#classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [31]:
# Adding the second hidden layer
#classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [32]:
# Adding the output layer
#classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [33]:
#compile the ANN
#classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [34]:
# Fitting the ANN to the Training set
#classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

In [35]:
# Predicting the Test set results
#y_pred = classifier.predict(X_test)

In [36]:
#y_pred

In [37]:
# threshold the probabilities into True > 0.5 or False
#y_pred = (y_pred > 0.5)

In [38]:
#y_pred

In [39]:
# computing the Confusion Matrix
#from sklearn.metrics import confusion_matrix

In [40]:
#cm = confusion_matrix(y_test, y_pred)

In [41]:
#cm

In [42]:
#(1525+197)/2000

In [43]:
# Predicting a single new observation
# request a prediction from the ANN using the new data formatted as needed
#new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3,
                                                           # 60000, 2, 1, 1, 50000]]))) 

In [44]:
#new_prediction

In [45]:
#new_prediction = (new_prediction > 0.5)

In [46]:
#new_prediction

In [47]:
# Evaluating the ANN
# load the libraries
#from keras.wrappers.scikit_learn import KerasClassifier
#from sklearn.model_selection import cross_val_score
#from keras.models import Sequential
#from keras.layers import Dense

In [48]:
#define our classifier
#def build_classifier():
 #   classifier = Sequential()
  #  classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
   # classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    #classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    #classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    #return classifier

In [49]:
# Run k-fold cross validation
# configure the classifier as needed; set the building function, the batch size and the number of epochs, as before
#classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 90)

In [50]:
# Run the k-fold cross validation; n_jobs = number of cpus, when set to -1 it means use all
#accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = 1)

In [51]:
#mean = accuracies.mean()

In [52]:
#variance = accuracies.std()

In [53]:
# add this library
from keras.layers import Dropout

In [54]:
# re-initialising the ANN
classifier = Sequential()

In [55]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 
'uniform', activation = 'relu', input_dim = 11)) 
classifier.add(Dropout(p = 0.1))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  after removing the cwd from sys.path.


In [56]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 
'uniform', activation = 'relu'))
classifier.add(Dropout(p = 0.1))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  after removing the cwd from sys.path.


In [57]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 
'uniform', activation = 'sigmoid'))

In [58]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 
'binary_crossentropy', metrics = ['accuracy'])

In [59]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 
100)

Epoch 1/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4937 - acc: 0.7956
Epoch 2/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4377 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 87us/step - loss: 0.4343 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 85us/step - loss: 0.4323 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 85us/step - loss: 0.4290 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 85us/step - loss: 0.4285 - acc: 0.7991
Epoch 7/100
8000/8000 [==============================] - 1s 85us/step - loss: 0.4290 - acc: 0.8240
Epoch 8/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.4287 - acc: 0.8227
Epoch 9/100
8000/8000 [==============================] - 1s 85us/step - loss: 0.4286 - acc: 0.8259
Epoch 10/100
8000/8000 [==============================] - 1s 86us/step - loss: 0.4270 - acc: 0.8266
Epoch 11

Epoch 83/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4236 - acc: 0.8336
Epoch 84/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.4258 - acc: 0.8291
Epoch 85/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4214 - acc: 0.8297
Epoch 86/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.4226 - acc: 0.8334
Epoch 87/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.4248 - acc: 0.8311
Epoch 88/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4209 - acc: 0.8334
Epoch 89/100
8000/8000 [==============================] - 1s 90us/step - loss: 0.4251 - acc: 0.8311
Epoch 90/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.4239 - acc: 0.8312
Epoch 91/100
8000/8000 [==============================] - 1s 88us/step - loss: 0.4245 - acc: 0.8310
Epoch 92/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.4229 - acc: 0.83

In [60]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
# threshold the probabilities into True > 0.5 or False
y_pred = (y_pred > 0.5) 

In [61]:
y_pred

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

In [62]:
# computing the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [63]:
cm

array([[1561,   34],
       [ 285,  120]])

In [64]:
(1561+120)/2000

0.8405

In [67]:
# Tuning the ANN
# load the libraries; note the Grid Search Cross Validation lib
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

In [68]:
#define our classifier
def build_classifier(
optimizer
):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [70]:
# Tuning the ANN
# configure the classifier as needed; set the building function
classifier = KerasClassifier(build_fn = build_classifier)

In [71]:
# enter different options for the batch size, the number of epochs and the optimizer:
parameters = {'batch_size': [25, 32],'epochs': [100, 500],'optimizer': ['adam', 'rmsprop']}

In [72]:
# Customize the Grid Search CV
grid_search = GridSearchCV(estimator = classifier,param_grid = parameters,scoring = 'accuracy',cv = 10)

In [ ]:
# fit the grid_search model to our training data
grid_search = grid_search.fit(X_train, y_train)